---
title: "Perform DINEOF"
---

## References

- https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2006JC003660
- https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2016GL071178

```{r}
library(metR)
library(data.table)
data(geopotential)
geopotential <- copy(geopotential)
geopotential[, gh.t.w := Anomaly(gh) * sqrt(cos(lat * pi / 180)),
    by = .(lon, lat, month(date))
]


head(training_data)

eof <- EOF(OC ~ lat + lon + TB | year + julianDay, 1:5,
    data = training_data,
    B = 100, probs = c(low = 0.1, hig = 0.9)
)

aao <- cut(eof, 1)
aao$sdev

library(ggplot2)
ggplot(aao$left, aes(lon, lat, z = OC)) +
    geom_contour(aes(color = after_stat(level))) 
```

```{r}
devtools::install_github("marchtaylor/sinkr")

# Make synthetic data field
m <- 50
n <- 100
frac.gaps <- 0.5 # the fraction of data with NaNs
N.S.ratio <- 0.1 # the Noise to Signal ratio for adding noise to data
x <- (seq(m) * 2 * pi) / m
t <- (seq(n) * 2 * pi) / n
Xt <- outer(sin(x), sin(t)) +
    outer(sin(2.1 * x), sin(2.1 * t)) +
    outer(sin(3.1 * x), sin(3.1 * t)) +
    outer(tanh(x), cos(t)) +
    outer(tanh(2 * x), cos(2.1 * t)) +
    outer(tanh(4 * x), cos(0.1 * t)) +
    outer(tanh(2.4 * x), cos(1.1 * t)) +
    tanh(outer(x, t, FUN = "+")) +
    tanh(outer(x, 2 * t, FUN = "+"))

# Color palette
pal <- colorRampPalette(c("blue", "cyan", "yellow", "red"))

#  The "true" fieldd
Xt <- t(Xt)

# The "noisy" field
set.seed(1)
RAND <- matrix(runif(length(Xt), min = -1, max = 1), nrow = nrow(Xt), ncol = ncol(Xt))
R <- RAND * N.S.ratio * Xt
Xp <- Xt + R

# The "observed" gappy field field
set.seed(1)
gaps <- sample(seq(length(Xp)), frac.gaps * length(Xp))
Xo <- replace(Xp, gaps, NaN)

# The dineof "interpolated" field
set.seed(1)
RES <- sinkr::dineof(Xo, delta.rms = 1e-02) # lower 'delta.rms' for higher resolved interpolation
Xa <- RES$Xa

# Visualization all fields
ZLIM <- range(Xt, Xp, Xo, Xa, na.rm = TRUE)
op <- par(mfrow = c(2, 2), mar = c(3, 3, 3, 1))
image(z = Xt, zlim = ZLIM, main = "A) True", col = pal(100), xaxt = "n", yaxt = "n", xlab = "", ylab = "")
box()
mtext("t", side = 1, line = 0.5)
mtext("x", side = 2, line = 0.5)
image(
    z = Xp, zlim = ZLIM, main = paste("B) True + Noise (N/S = ", N.S.ratio, ")", sep = ""),
    col = pal(100), xaxt = "n", yaxt = "n", xlab = "", ylab = ""
)
box()
mtext("t", side = 1, line = 0.5)
mtext("x", side = 2, line = 0.5)
box()
image(
    z = Xo, zlim = ZLIM, main = paste("C) Observed (", frac.gaps * 100, " % gaps)", sep = ""),
    col = pal(100), xaxt = "n", yaxt = "n", xlab = "", ylab = ""
)
mtext("t", side = 1, line = 0.5)
mtext("x", side = 2, line = 0.5)
image(
    z = Xa, zlim = ZLIM, main = "D) Reconstruction", col = pal(100), xaxt = "n", yaxt = "n",
    xlab = "", ylab = ""
)
box()
mtext("t", side = 1, line = 0.5)
mtext("x", side = 2, line = 0.5)
par(op)

```
