project:
  type: website
  output-dir: docs

website:
  title: "Sea surface salinity interpolation"
  reader-mode: true
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Data preparation"
        contents:
          - 1-preparation/index.qmd
          - 2-transformation/index.qmd
    tools:
      - icon: github
        href: https://github.com/SteveViss/seaSurfaceSalinity-DFO

format:
  html:
    theme: cosmo
    toc: true
